@Cyex_HostAddress = http://localhost:8080/

POST {{Cyex_HostAddress}}/api/v1/Scan
Content-Type: application/json

{
  "ecosystem": "npm",
  "fileContent": "ewogICJuYW1lIjogIk15IEFwcGxpY2F0aW9uIiwKICAidmVyc2lvbiI6ICIxLjAuMCIsCiAgImRlcGVuZGVuY2llcyI6IHsKICAgICJkZWVwLW92ZXJyaWRlIjogIjEuMC4xIiwKICAgICJleHByZXNzIjogIjQuMTcuMSIKICB9Cn0="
}

###